### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Dontorpedo** [techouse/total-records#1]
Hi,

all my total records show zero, tried different resources but all all cards show zero... :(

**Comment by techouse** [comment]
Hmm, you are supposed to pass in a `Model`, not a `Nova\Resource`. Try passing in `App\User::class`. It should work since it basically just calls the `count()` static method on that `Model`. 

Also check your error log for clues and report back please. 😊

P.S. Version 1.1.0 had a bug. Please use either 1.0.0 or 1.1.1.
